version: "3.9"

services:
  web:
    build: .
    container_name: fastapi_linebot
    ports:
      - "8000:8000"
    environment:
      - LINE_CHANNEL_SECRET = line_channel_secret
      - CHANNEL_ACCESS_TOKEN = channel_access_token
      - DATABASE_URL=postgresql://postgres:password@db:5432/fastapi_linebot
    depends_on:
      - db
  
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: