name: Deploy to EC2 (Amazon Linux 2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Remote deploy to Amazon Linux 2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # port: 22   # 変更していなければ省略可
          script: |
            set -euo pipefail

            # 1) (初回のみ) Docker & Compose プラグインが無ければインストール
            if ! command -v docker &>/dev/null; then
              sudo yum update -y
              sudo amazon-linux-extras install docker -y
              sudo yum install -y docker-compose-plugin
              sudo systemctl enable --now docker
              sudo usermod -aG docker $USER   # 次回以降 sudo 不要
              echo "Docker installed."
            fi

            # 2) リポジトリへ移動して更新
            cd ./Linebot   # 適宜変更
            git pull origin main

            # 3) コンテナ再ビルド & 再起動
            docker compose up -d --build
