name: Deploy via SSM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # OIDC トークン取得を許可
      contents: read     # actions/checkout のため

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send command via SSM
        uses: MercuryTechnologies/aws-ssm-send-command-action@main
        with:
          document-name: AWS-RunShellScript
          targets: '[{"Key":"instanceids","Values":["${{ secrets.EC2_INSTANCE_ID }}"]}]'
          parameters: >-
            {"commands":[
               "cd ~/Linebot",
               "git pull origin main",
               "cat > .env <<EOF\nPOSTGRES_USER=***\nPOSTGRES_PASSWORD=***\nPOSTGRES_DB=***\nEOF",
               "chmod 600 .env",
               "docker compose up -d --build",
               "rm -f .env"
            ]}
          wait-until-command-executed: true    
          max-wait-time: 600                  
          log-failed-command-invocations: true  
