name: Deploy to EC2 (Amazon Linux 2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Remote deploy to Amazon Linux 2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail

            ##### 1) アプリケーション取得／更新 #####
            cd ~/Linebot              # デプロイ先ディレクトリに合わせて変更
            git pull origin main

            ##### 2) 秘密情報入り .env を生成（毎回上書き） #####
            cat > .env << 'EOF'
            
            # --- PostgreSQL ---
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}

            EOF
            chmod 600 .env

            ##### 3) コンテナ再ビルド & 再起動 #####
            docker compose up -d --build

            # スクリプト終了時に .env を確実に消す
            trap 'rm -f .env' EXIT
